/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS `device_no` (
  `id` int(5) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `device_code` varchar(32) DEFAULT NULL COMMENT '设备型号code',
  `device_name` varchar(32) DEFAULT NULL COMMENT '设备型号名称',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='设备型号表';

DELETE FROM `device_no`;
/*!40000 ALTER TABLE `device_no` DISABLE KEYS */;
INSERT INTO `device_no` (`id`, `device_code`, `device_name`) VALUES
	(1, 'lamp_v1', '第一代智能台灯');
/*!40000 ALTER TABLE `device_no` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
